### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by 19giovi87** [QuakeMigrate/QuakeMigrate#131]
**Describe the bug**
After the creation of the conda environment, the command `$ pip install .` fails to install quakemigrate.
Main error is:
`error: command 'gcc' failed with exit status 1`
See attachment for the complete error screendump.

**To Reproduce**
- Create the conda environment wit the requisites specified in quakemigrate.yml
`$ conda env create -f quakemigrate.yml`
- Activate environment and run 
`$ pip install .`

**Expected behavior**
Quakemigrate should be correctly installed 

**Desktop (please complete the following information):**
 - MacOS: 11.5.2 
 - Python version: 3.8.12
 - QuakeMigrate version: latest

**Additional context**
Gcc is installed 

```
$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-apple-darwin14.4.0/5.1.0/lto-wrapper
Target: x86_64-apple-darwin14.4.0
Configured with: ../gcc-5.1.0/configure --enable-languages=c++,fortran
Thread model: posix
gcc version 5.1.0 (GC
```
[error1.txt](https://github.com/QuakeMigrate/QuakeMigrate/files/7249710/error1.txt)

**Comment by hemmelig** [comment]
Hi Giovanni

So I've just been through the process of installing QuakeMigrate on Big Sur. I found the best solution to be to install GCC via brew

```
brew install gcc@9
brew link gcc
```

I then had to check which `gcc` had priority in the path. I recommend `/usr/local/bin`. Here, I created a symbolic link to the gcc-9 installed via homebrew using:

```
ln -s <target_path> <link_path>
```

Where target_path is the gcc-9 compiler in your homebrew 'Cellar', and the link path is in `/usr/local/bin`. You may need to edit your `$PATH` variable to ensure `/usr/local/bin` has priority.

Once you've done this, you should hopefully be able to do `which gcc` and `gcc -v` and see they now point to the right compilers.

Then try `pip install .` once more.

**Comment by 19giovi87** [comment]
Hi hemmelig, thanks for your reply.

I just got stuck at 

`$ ln -s /usr/local/Cellar/gcc-9 /usr/local/bin/gcc
`
Giving `/usr/local/bin/gcc: File exists`. Gcc appears to be linked to the previous version...

How to solve this?

**Comment by hemmelig** [comment]
You can make a backup of that file/link using `mv /usr/local/bin/gcc /usr/local/bin/gcc_old` then try making the link again.

**Comment by 19giovi87** [comment]
Hi hemmelig,

I've done what you suggest. I added `/usr/local/bin` to ~/.bash_profile with: 
`export PATH="/usr/local/bin:$PATH"
`
However gcc seems to be still linked to usr/bin/gcc and installation fails. What am I doing wrong?

**Comment by hemmelig** [comment]
Can you share the outputs of `which gcc` and `gcc -v` here? Did you restart your shell session after changing your bash profile?

**Comment by 19giovi87** [comment]
Yes, I've restarted it.
`which gcc` --->  `/usr/bin/gcc`
`gcc -v` --->
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by hemmelig** [comment]
Ok - can you share the output of `echo $PATH` and `ls -lh /usr/local/bin/gcc*`?

It appears that either the symlink you made to the brew installed version of gcc is silently failing and it is seeking the next version of gcc in your path, or `/usr/bin` has a higher priority.

**Comment by 19giovi87** [comment]
`$ echo $PATH` `/Users/giovanni_work/anaconda3/envs/eqcorrscan/bin:/Users/giovanni_work/anaconda3/condabin:/Users/giovanni_work/miniconda3/bin:/Users/giovanni_work/Documents/Dottorato/Resources/latexdiff:/opt/local/bin:/opt/local/sbin:/Applications/gut-3.1/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Applications/Perplex:/usr/local/opt/python/libexec/bin:/usr/local/bin/gcc:/Applications/gut-3.1/bin:/Applications/gut-3.1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Users/giovanni_work/Documents/Dottorato/Resources/sac/bin:/Applications/Tesseroids/bin:/Applications/MATLAB_R2017a.app/bin:/Applications/NLLOC:/Users/giovanni_work/Documents/Dottorato/Resources/FMTOMO/fmtomov1.0/bin`

`$ ls -lh /usr/local/bin/gcc*
`
```
lrwxr-xr-x  1 giovanni_work  wheel    23B  5 Ott 10:05 /usr/local/bin/gcc -> /usr/local/Cellar/gcc-9
lrwxr-xr-x  1 giovanni_work  wheel    31B  5 Ott 10:00 /usr/local/bin/gcc-11 -> ../Cellar/gcc/11.2.0/bin/gcc-11
lrwxr-xr-x  1 giovanni_work  wheel    31B  5 Ott 09:37 /usr/local/bin/gcc-9 -> ../Cellar/gcc@9/9.4.0/bin/gcc-9
-rwxr-xr-x  1 giovanni_work  wheel    42K 29 Mag  2015 /usr/local/bin/gcc-ar
lrwxr-xr-x  1 giovanni_work  wheel    34B  5 Ott 10:00 /usr/local/bin/gcc-ar-11 -> ../Cellar/gcc/11.2.0/bin/gcc-ar-11
lrwxr-xr-x  1 giovanni_work  wheel    34B  5 Ott 09:37 /usr/local/bin/gcc-ar-9 -> ../Cellar/gcc@9/9.4.0/bin/gcc-ar-9
-rwxr-xr-x  1 giovanni_work  wheel    42K 29 Mag  2015 /usr/local/bin/gcc-nm
lrwxr-xr-x  1 giovanni_work  wheel    34B  5 Ott 10:00 /usr/local/bin/gcc-nm-11 -> ../Cellar/gcc/11.2.0/bin/gcc-nm-11
lrwxr-xr-x  1 giovanni_work  wheel    34B  5 Ott 09:37 /usr/local/bin/gcc-nm-9 -> ../Cellar/gcc@9/9.4.0/bin/gcc-nm-9
-rwxr-xr-x  1 giovanni_work  wheel    42K 29 Mag  2015 /usr/local/bin/gcc-ranlib
lrwxr-xr-x  1 giovanni_work  wheel    38B  5 Ott 10:00 /usr/local/bin/gcc-ranlib-11 -> ../Cellar/gcc/11.2.0/bin/gcc-ranlib-11
lrwxr-xr-x  1 giovanni_work  wheel    38B  5 Ott 09:37 /usr/local/bin/gcc-ranlib-9 -> ../Cellar/gcc@9/9.4.0/bin/gcc-ranlib-9
-rwxr-xr-x  1 giovanni_work  wheel   1,2M 29 Mag  2015 /usr/local/bin/gcc_old
```

**Comment by hemmelig** [comment]
Ah, apologies, I think I see the issue now - the link doesn't point to the compiler. You can delete `/usr/local/bin/gcc` and make a new link as follows:

`ln -s /usr/local/bin/gcc-9 /usr/local/bin/gcc`

It was failing silently previously. Try that and let me know the output of `gcc -v` and `which gcc` and try compiling again.

**Comment by 19giovi87** [comment]
Now the gcc version appears to be correct, but still compilation isn't working :( (see attachment)

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/Cellar/gcc@9/9.4.0/libexec/gcc/x86_64-apple-darwin20/9.4.0/lto-wrapper
Target: x86_64-apple-darwin20
Configured with: ../configure --prefix=/usr/local/Cellar/gcc@9/9.4.0 --libdir=/usr/local/Cellar/gcc@9/9.4.0/lib/gcc/9 --disable-nls --enable-checking=release --enable-languages=c,c++,objc,obj-c++,fortran --program-suffix=-9 --with-gmp=/usr/local/opt/gmp --with-mpfr=/usr/local/opt/mpfr --with-mpc=/usr/local/opt/libmpc --with-isl=/usr/local/opt/isl --with-pkgversion='Homebrew GCC 9.4.0' --with-bugurl=https://github.com/Homebrew/homebrew-core/issues --build=x86_64-apple-darwin20 --with-system-zlib --disable-multilib --without-build-config --with-native-system-header-dir=/usr/include --with-sysroot=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
Thread model: posix
gcc version 9.4.0 (Homebrew GCC 9.4.0)
```
`/usr/local/bin/gcc
[error1.txt](https://github.com/QuakeMigrate/QuakeMigrate/files/7284421/error1.txt)
`

**Comment by hemmelig** [comment]
Ok - I don't think we have come across this one before. It looks to me like your system is finding the wrong Assembler (in `/opt/local/bin` rather than `/usr/bin`). Can you do `which as`? I would make sure that `/usr/local/bin:/usr/bin` is at the head of your path variable, then try again.

**Comment by 19giovi87** [comment]
Ok, I've put export `PATH="/usr/local/bin:/usr/bin:${PATH}"` in my ./bash_profile . Restarted the kernel and `which as` is still
`/opt/local/bin` and installation fails.

**Comment by TomWinder** [comment]
I think it's possible your issue is similar to what is reported here: https://github.com/dmlc/xgboost/issues/1945#issuecomment-370475958

Can you do `echo $PATH` to check? Then the solution will be to edit or remove the `.profile` file (if that exists!) to stop it putting `/opt/local/bin` at the head of your path.

**Comment by 19giovi87** [comment]
Hi @TomWinder , the solution proposed in the link worked like a charm. Thank you very much for the hint!
