### ISSUE TITLE
Error when no earthquke in trigger step.

### ISSUE THREAD

**Issue by MattisGr** [QuakeMigrate/QuakeMigrate#133]
**Describe the bug**
Trigger code stops with an error when there isn't any earthquake during a day. 

**To Reproduce**
To reproduce the error, compute the trigger plot on a day without earthquake in an area or use an higher detection threshold to avoid detecting earthquake. The error message says "local variable 'discarded' referenced before assignment" in ~/miniconda3/envs/quakemigrate/lib/python3.8/site-packages/quakemigrate/signal/trigger.py (line 299) when using the function trig.trigger. 
I looked at it and it is at line 279 :

        if candidate_events.empty:
            logging.info("\tNo events triggered at this threshold - try a "
                         "lower detection threshold.")
            events = candidate_events
        else:
            refined_events = self._refine_candidates(candidate_events)
            events = self._filter_events(refined_events, batchstart, batchend,
                                         region)
            discarded = refined_events[~refined_events.isin(events)].dropna() #this variable is only defined here and not in the first condition
            logging.info(f"\n\t\t{len(events)} event(s) triggered within the "
                         f"specified region between {batchstart} \n\t\tand "
                         f"{batchend}")
            logging.info("\n\tWriting triggered events to file...")
            write_triggered_events(self.run, events, batchstart)

        if self.plot_trigger_summary:
            logging.info("\n\tPlotting trigger summary...")
            trigger_summary(events, batchstart, batchend, self.run,
                            self.marginal_window, self.min_event_interval,
                            threshold, self.normalise_coalescence, self.lut,
                            data, region, discarded,   #here is the problem
                            interactive=interactive_plot,
                            xy_files=self.xy_files,
                            plot_all_stns=self.plot_all_stns)             

If the code go to the first if and then to the second one, discarded is not defined and an error occurs. 

**Expected behavior**
I just expect to have either a trigger summary plot without any earthquake at this day or just skip the plot if it is not mandatory for the locate step. 

**Desktop (please complete the following information):**
 - Operating System: Ubuntu 20.04.3 LTS
 - Python version: 3.8.12
 - QuakeMigrate version: 1.0.0

**Additional context**
I am running it on a different computer (uranus) and I had on problem before with the version of one function too.

**Comment by TomWinder** [comment]
Yep - thanks for submitting Mattis. Had forgotten we had come across (and fixed) this before.. see #125 and f03b290. That commit is only in `maintenance_1.0.0` at the moment, though; not merged into `master`.
