### ISSUE TITLE
ImportError: Could not load extension library 'qmlib'.

### ISSUE THREAD

**Issue by glPeng-seis** [QuakeMigrate/QuakeMigrate#136]
I installed quakemigrate according to the steps of the instructions. But I still meet a problem, like this:
===================================
```
>>> import quakemigrate
Traceback (most recent call last):
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/libnames.py", line 39, in _load_cdll
    cdll = ctypes.CDLL(str(lib))
  File "/Users/guanlingpeng/anaconda3/envs/quakemigrate/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/src/qmlib.cpython-37m-darwin.so, 0x0006): tried: '/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/src/qmlib.cpython-37m-darwin.so' (no such file), '/usr/local/lib/qmlib.cpython-37m-darwin.so' (no such file), '/usr/lib/qmlib.cpython-37m-darwin.so' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/__init__.py", line 18, in <module>
    from quakemigrate.signal import QuakeScan, Trigger  # NOQA
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/signal/__init__.py", line 20, in <module>
    from .scan import QuakeScan  # NOQA
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/signal/scan.py", line 23, in <module>
    from quakemigrate.core import find_max_coa, migrate
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/__init__.py", line 20, in <module>
    from .lib import migrate, find_max_coa  # NOQA
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/lib.py", line 20, in <module>
    qmlib = _load_cdll("qmlib")
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/libnames.py", line 45, in _load_cdll
    raise ImportError(msg)
ImportError: Could not load extension library 'qmlib'.

dlopen(/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/src/qmlib.cpython-37m-darwin.so, 0x0006): tried: '/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/src/qmlib.cpython-37m-darwin.so' (no such file), '/usr/local/lib/qmlib.cpython-37m-darwin.so' (no such file), '/usr/lib/qmlib.cpython-37m-darwin.so' (no such file)

If you have chosen to install from a clone of the github repository, please ensure you have run 'python setup.py install', which will compile and install the C library. See the installation documentation for more details.
```

===================================
I don't know how to solve it.

**Comment by TomWinder** [comment]
Hi, please provide information as requested in the template:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behaviour (including error messages if applicable).

**Expected behavior**
A clear and concise description of what you expected to happen.

**Desktop (please complete the following information):**
 - Operating System:
 - Python version:
 - QuakeMigrate version:

**Additional context**
Add any other context about the problem here.

**Comment by hemmelig** [comment]
Similar to Issue #129 - once you've provided the above, can you also try the suggestions provided there?

**Comment by glPeng-seis** [comment]
> Similar to Issue #129 - once you've provided the above, can you also try the suggestions provided there?

Oh my god, I still don't know how to solve it！！

**Comment by hemmelig** [comment]
Can you provide the information that Tom requested above? In particular, the operating system and where in your path you are running the `import quakemigrate` command.

Thank you.

**Comment by glPeng-seis** [comment]
**Describe the bug**
After installed QuakeMigrate, accessing python to execute “import quakemigrate”, prompting the problem.

**To Reproduce**
>>> import quakemigrate
Traceback (most recent call last):
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/libnames.py", line 39, in _load_cdll
    cdll = ctypes.CDLL(str(lib))
  File "/Users/guanlingpeng/anaconda3/envs/quakemigrate/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/src/qmlib.cpython-37m-darwin.so, 0x0006): tried: '/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/src/qmlib.cpython-37m-darwin.so' (no such file), '/usr/local/lib/qmlib.cpython-37m-darwin.so' (no such file), '/usr/lib/qmlib.cpython-37m-darwin.so' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/__init__.py", line 18, in <module>
    from quakemigrate.signal import QuakeScan, Trigger  # NOQA
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/signal/__init__.py", line 20, in <module>
    from .scan import QuakeScan  # NOQA
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/signal/scan.py", line 23, in <module>
    from quakemigrate.core import find_max_coa, migrate
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/__init__.py", line 20, in <module>
    from .lib import migrate, find_max_coa  # NOQA
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/lib.py", line 20, in <module>
    qmlib = _load_cdll("qmlib")
  File "/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/libnames.py", line 45, in _load_cdll
    raise ImportError(msg)
ImportError: Could not load extension library 'qmlib'.

dlopen(/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/src/qmlib.cpython-37m-darwin.so, 0x0006): tried: '/Users/guanlingpeng/QuakeMigrate/quakemigrate/core/src/qmlib.cpython-37m-darwin.so' (no such file), '/usr/local/lib/qmlib.cpython-37m-darwin.so' (no such file), '/usr/lib/qmlib.cpython-37m-darwin.so' (no such file)

If you have chosen to install from a clone of the github repository, please ensure you have run 'python setup.py install', which will compile and install the C library. See the installation documentation for more details.

**Expected behavior**
Miss the file 'qmlib.cpython-37m-darwin.so'

**Desktop (please complete the following information):**

Operating System: macOS Monterey
Python version: Python=3.7
QuakeMigrate version: Version=1.0.0

**In addition, the path of running 'import quakemigrate'**
In the downloaded package ‘QuakeMigrate’

**Comment by hemmelig** [comment]
Great, thanks - can you run the following in terminal and paste the full outputs here:

1. Test if the compiled _shared object_ is installed in the conda environment
```
ls /Users/guanlingpeng/anaconda3/envs/quakemigrate/lib/python3.7/site-packages/quakemigrate/core/src
```
If there is a file that looks like `qmlib.cpython-37m-darwin.so`, then the issue is related to #129 - if you change directory to anywhere but `/Users/guanlingpeng/QuakeMigrate` (such as `/Users/guanlingpeng/QuakeMigrate/examples`) and try again. Or you could switch to the `tests` directory and try running the tests.

If the file is not there, then it suggests an issue when the core routines are being compiled. We have encountered issues with Mac compilers in the past, so it is not unheard of. If this is the case, you can rerun `pip install .` in the base QuakeMigrate directory and share the entire output here.

2. Check compiler version you have installed and where. In terminal, with your environment activated to be sure, enter:
```
gcc -v
which gcc
```

We should be able to troubleshoot any issues with this information.

**Comment by glPeng-seis** [comment]
It is OK when install pyqt.

**Comment by TomWinder** [comment]
@glPeng-seis Please can you confirm that this is issue is now resolved, after changing directory and sorting out pyqt? Cheers.

**Comment by GPeng00** [comment]
@TomWinder Yes, this issue is resolved, after changing directory and installing pyqt 5.9.2.
Thank you very much!
