### ISSUE TITLE
error in compute_traveltimes

### ISSUE THREAD

**Issue by fontiela** [QuakeMigrate/QuakeMigrate#139]
When I compute_traveltimes with "homogenous" method it works perfect, but when I use one of the other methods I get an error calculating the travel times to S phase. It's very strange, since it computes the travel times to the first station and the error shows-up on the second one. The output and error are the following;

```
Computing 1-D nlloc traveltimes for...
	...phase: P...
		...running Grid2Time - station: ADH   - 1 of 13
		...running Grid2Time - station: CALA  - 2 of 13
		...running Grid2Time - station: HOR   - 3 of 13
		...running Grid2Time - station: PAGU  - 4 of 13
		...running Grid2Time - station: PCAN  - 5 of 13
		...running Grid2Time - station: PCED  - 6 of 13
		...running Grid2Time - station: PGRA  - 7 of 13
		...running Grid2Time - station: PICO  - 8 of 13
		...running Grid2Time - station: PID   - 9 of 13
		...running Grid2Time - station: PMAN  - 10 of 13
		...running Grid2Time - station: PPNO  - 11 of 13
		...running Grid2Time - station: PSCM  - 12 of 13
		...running Grid2Time - station: ROSA  - 13 of 13
	...phase: S...
		...running Grid2Time - station: ADH   - 1 of 13
		...running Grid2Time - station: CALA  - 2 of 13
Traceback (most recent call last):
  File "/Users/joaofontiela/Documents/PycharmProjects/Earthquake_detection/sjo_teste.py", line 172, in <module>
    lut = compute_traveltimes(grid_spec, stations, method="1dnlloc", vmod=vmodel,
  File "/Users/joaofontiela/opt/anaconda3/envs/quakemigrate/lib/python3.8/site-packages/quakemigrate/lut/create_lut.py", line 212, in compute_traveltimes
    _compute_1d_nlloc(lut, phase, vmodel, **kwargs)
  File "/Users/joaofontiela/opt/anaconda3/envs/quakemigrate/lib/python3.8/site-packages/quakemigrate/lut/create_lut.py", line 455, in _compute_1d_nlloc
    out = check_output([str(nlloc_path / mode),
  File "/Users/joaofontiela/opt/anaconda3/envs/quakemigrate/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/joaofontiela/opt/anaconda3/envs/quakemigrate/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['Vel2Grid', 'control.in']' returned non-zero exit status 252.
```

My system is a macOS 12.4 and ` conda version : 4.12.0` ,`conda-build version : 3.21.4`, `python version : 3.8.11.final.0` and `quakemigrate 1.0.0  `

**Comment by hemmelig** [comment]
Could you share the script you are using to build the LUT, your station file, and the velocity model file? I can then try and reproduce the error on my end.

**Comment by fontiela** [comment]
Hi @hemmelig 
Thank you for your fast reply. Find attached the files you asked. Please, replace the file extension of teste.txt by *.py.   
[teste.txt](https://github.com/QuakeMigrate/QuakeMigrate/files/8933953/teste.txt)
[sjo_vmodel.txt](https://github.com/QuakeMigrate/QuakeMigrate/files/8933956/sjo_vmodel.txt)
[centralgroup_stations.txt](https://github.com/QuakeMigrate/QuakeMigrate/files/8933957/centralgroup_stations.txt)

**Comment by hemmelig** [comment]
Ok - using your files, I also got your error. The issue is you are providing the station elevations in metres, but specifying the LUT (and the velocity model) with units of **kilo**metres.

Corrected file:
[centralgroup_stations.txt](https://github.com/QuakeMigrate/QuakeMigrate/files/8934464/centralgroup_stations.txt)

After correcting the elevations, everything runs fine! Let me know if that resolves things for you too, and I'll close this issue.

**Comment by fontiela** [comment]
@hemmelig, thanks a lot for your time. It's working fine.
