### ISSUE TITLE
Overlapping waveforms in locate plot summary

### ISSUE THREAD

**Issue by PhilCryo** [QuakeMigrate/QuakeMigrate#142]
Hi,

**Describe the bug**
It is not really a bug. I'm dealing with an array of 4 to 6 stations so the output pdf file contains a plot with 4 to 6 waveforms corresponding to the event. If I have a seismic event close to one station, the amplitude is really different from one waveform to the other (10 times larger sometimes) and, thus, the plot of waveforms is not really readable (overlapping waveforms) (scaling seems to be made over the smaller amplitude waveform and not on each waveforms). I tried to find some info in quakemigrate.plot docs but I didn't find.

Do you have an idea where I could find some parameters that could be changed to fix this issue?

**To Reproduce**
Just using the different steps of QM and reading the output pdf file of locate.

**Expected behavior**
I would like to adjust the scales (y values) of each waveform in the output pdf file of locate.

**Desktop (please complete the following information):**

    Operating System: Debian GNU/ Linux 10
    Python version: 3.8.13
    QuakeMigrate version: 1.0.0

**Additional context**
Please find attached a pdf file as an example.

Phil

[icequake_example_Astrolabe_20220115021309825_EventSummary.pdf](https://github.com/QuakeMigrate/QuakeMigrate/files/9149873/icequake_example_Astrolabe_20220115021309825_EventSummary.pdf)

**Comment by PhilCryo** [comment]
Hi!

Thanks for the reply and for the comments ! 
Indeed, I wanted to model only one phase, but doing that, it only selects one component (the Z channel) for the different steps. Is it possible to change the component which is used to detect/trigger/locate ? Or to do the analysis with the 3 components ?

Concerning the amplitude scaling, I increased the 1.5 factor with different values, it seems to work well!

Thanks again, 

Phil

**Comment by TomWinder** [comment]
No problem.

Yes - good question. You can customise the channels used when specifying the onset function parameters. E.g. the code below would create just a P onset function, and using all channels (with channel codes ending Z, N, E, 1, 2 .. you can customise this as you like - it is passed to obspy.Stream.select(channel=<pattern>) ).

```
# --- Create new Onset ---
onset = STALTAOnset(position="classic", sampling_rate=50)
onset.phases = ["P"]
onset.bandpass_filters = {
    "P": [2, 16, 2]}
onset.sta_lta_windows = {
    "P": [0.2, 1.0]}
onset.channel_maps = {
    "P": "*[Z,N,E,1,2]"})
```

We still need to add this to the available examples / documentation!

**Comment by PhilCryo** [comment]
Thanks!
