### ISSUE TITLE
AttributeError: module 'numpy' has no attribute 'bool'.

### ISSUE THREAD

**Issue by VolcanomanSamUEA** [QuakeMigrate/QuakeMigrate#148]
I am receiving an attribute error relating to numpy when importing from quakemigrate.io / .lut.

Code to reproduce:
from quakemigrate.io import read_stations
from quakemigrate.lut import compute_traveltimes

 - Operating System: Win10
 - Python version: 3.8.16
 - QuakeMigrate version: 1.0.0
 - Numpy version: 1.24.2

Full Error:
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    [https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnumpy.org%2Fdevdocs%2Frelease%2F1.20.0-notes.html%23deprecations&data=05%7C01%7CS.Mitchinson%40uea.ac.uk%7Caf12a406e4e94a2bbf1708db2acfd8c9%7Cc65f8795ba3d43518a070865e5d8f090%7C0%7C0%7C638150844405049905%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eRCmAALyGQ1LS0XbWNBarA2ujpNHQWEV1%2FE9m9bM36E%3D&reserved=0)

**Comment by TomWinder** [comment]
Thanks for posting Sam. Please will you also check what numpy version you are running? (Should be possible with `conda list` and then search for the numpy line).

**Comment by VolcanomanSamUEA** [comment]
> Thanks for posting Sam. Please will you also check what numpy version you are running? (Should be possible with `conda list` and then search for the numpy line).

Added above (Numpy v 1.24.2)

**Comment by VolcanomanSamUEA** [comment]
Changing my numpy version to 1.23 fixed the AttributeError: module 'numpy' has no attribute 'bool'. 

Thank you!

**Comment by TomWinder** [comment]
(Leaving this as an open issue until this has been dealt with in the master branch.)

**Comment by TomWinder** [comment]
Closed with #138
