### ISSUE TITLE
Tests timing out on data acquisition from EarthScope stage

### ISSUE THREAD

**Issue by hemmelig** [QuakeMigrate/QuakeMigrate#172]
**Describe the bug**
Not strictly a bug, but the tests are failing for, I believe, reasons of being timed out by the EarthScope DMC. They've recently moved to using a cloud platform for their services, so this could be a protection measure that stops them from being swamped with excessive requests? We might consider moving the example waveform files to a dedicated Zenodo and using curl/wget to retrieve them, then unpack them.

**To Reproduce**
Based on the reports from the last automated test run.

**Expected behavior**
The tests should run without issue.

**Comment by TomWinder** [comment]
If it's definitely an anti-spam problem (seems likely, though couldn't immediately see any bug reports about this on obspy etc), then I think there are ~ 3 options:
1. Zenodo, as suggested
2. Look into using the [mass_downloader](https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.mass_downloader.html#module-obspy.clients.fdsn.mass_downloader) -- but for this particular example I think this is probably overkill. I was sure I'd written a neat script using this for the forthcoming Askja example, but I can't find it right now..
3. edit the download script to just make one request, with all stations (checked this manually and it's also way faster):

```
station_string = ",".join(stations["Name"])
```

-->
```diff
@@ -29,17 +29,16 @@ endtime = UTCDateTime("2014-236T00:15:00")

#  --- Read in station file ---
 stations = read_stations(station_file)
+stations_string = ",".join(stations["Name"])
 
 # --- Download instrument response inventory ---
-inv = Inventory()
-for station in stations["Name"]:
-    inv += client.get_stations(
-        network=network,
-        station=station,
-        starttime=starttime,
-        endtime=endtime,
-        level="response",
-    )
+inv = client.get_stations(
+    network=network,
+    station=stations_string,
+    starttime=starttime,
+    endtime=endtime,
+    level="response",
+)
 inv.write(response_file, format="STATIONXML")
 
 # --- Make directories to store waveform data ---
@@ -47,20 +46,22 @@ waveform_path = data_path / str(starttime.year) / f"{starttime.julday:03d}"
 waveform_path.mkdir(parents=True, exist_ok=True)
 
 # --- Download waveform data ---
+print(f"Downloading waveform data from {datacentre}")
+st = client.get_waveforms(
+    network=network,
+    station=stations_string,
+    location="*",
+    channel="*H*",
+    starttime=starttime,
+    endtime=endtime,
+)
+st.merge(method=-1)
+
 for station in stations["Name"]:
-    print(f"Downloading waveform data for station {station} from {datacentre}")
-    st = client.get_waveforms(
-        network=network,
-        station=station,
-        location="*",
-        channel="*H*",
-        starttime=starttime,
-        endtime=endtime,
-    )
-    st.merge(method=-1)
+    print(f"Writing data from station {station} to disk")
     for comp in ["E", "N", "Z"]:
         try:
-            st_comp = st.select(component=comp)
+            st_comp = st.select(station=station, component=comp)
             st_comp.write(str(waveform_path / f"{station}_{comp}.m"), format="MSEED")
         except IndexError:
             pass
```

**Comment by TomWinder** [comment]
Can commit and check this now, though difficult to be 100% certain if it will reliably fix the problem I guess..

**Comment by hemmelig** [comment]
Worth a go, I like the ObsPy/FDSN script, as it's obviously useful as an example of how someone might handle it.

That's just my best guess—the fact that one test was successful, then all of the others failed because they timed out on that stage pointed me that way. Could be wrong, of course, but if you create a branch with the prefix `bugfix/` and make that change, we'll find out!

**Comment by TomWinder** [comment]
...seems to have worked this time, at least!

**Comment by hemmelig** [comment]
Great, let's pull and merge it—definitely worthwhile just for the speed improvement of acquisition.

**Comment by hemmelig** [comment]
PR addressing this merged. Closing.
