### ISSUE TITLE
examples program expand longitude can‘t run detect

### ISSUE THREAD

**Issue by zhangdalang** [QuakeMigrate/QuakeMigrate#176]
Hi,English is not my native language, I hope you can understand it. I sorry about this.
Im running the examples/Icequake_Iceland/iceland_lut.py and iceland_detect.py.They are working very well.
Then I trying expand longitude in iceland_lut.py like this and run it again:
```
grid_spec.ll_corner = [-19.24363934275664, 64.31947715407385, -1.390]
grid_spec.ur_corner = [-15.204348515198255, 64.3365202025144, 1.390]
```
A new Lut file has been generated in outputs/lut. So far, the program has been fine.

But when I run the iceland_detect.py again, and I'm not edit this file.
The result every timestep is like this:

> Processing : 2014-06-29T18:41:55.000000Z-2014-06-29T18:41:55.750000Z ~~~~~~~~~~~~~~~~~~~~
> 		No P onset for SKR01.
> 		No P onset for SKR02.
> 		No P onset for SKR03.
> 		No P onset for SKR04.
> 		No P onset for SKR05.
> 		No P onset for SKR06.
> 		No P onset for SKR07.
> 		No P onset for SKG08.
> 		No P onset for SKG09.
> 		No P onset for SKG10.
> 		No P onset for SKG11.
> 		No P onset for SKG12.
> 		No P onset for SKG13.
> 		No S onset for SKR01.
> 		No S onset for SKR02.
> 		No S onset for SKR03.
> 		No S onset for SKR04.
> 		No S onset for SKR05.
> 		No S onset for SKR06.
> 		No S onset for SKR07.
> 		No S onset for SKG08.
> 		No S onset for SKG09.
> 		No S onset for SKG10.
> 		No S onset for SKG11.
> 		No S onset for SKG12.
> 		No S onset for SKG13.
> 		All data for this timestep failed to pass the
> 		specified data quality criteria. This includes the
> 		presence of gaps or overlaps, or the data not
> 		spanning the full time window.

In the _Tutorials 2.1.1.2. Geographical location and spatial extent_, I saw a Note ,that is _"you are free to design the grid as you wish."_
I don't know why after expanding the volume，the iceland_detect.py file is doesn't work.
Looking forward to your reply, thank you so much.

**Comment by hemmelig** [comment]
Hi, thanks for raising this! Can you confirm a few things for me, and I'll take a look at it:

- Your operating system
- The version of QuakeMigrate you are using

Cheers!

**Comment by hemmelig** [comment]
One quick comment is that using a 4 degree wide lookup table, at 0.1 km resolution, will lead to an extremely large search grid!

**Comment by hemmelig** [comment]
Ok—I figured out the issue. While we perform our searches over a finite time step (in this case, 0.75 seconds), in order to properly perform the migration and stacking across the whole search volume, we need some additional time series data before and after. The amount is controlled by the maximum travel time across the grid—in this case, because the grid is so large, we require a large amount of time series data to properly perform the search. The example only includes a small snippet of data, which is shorter than would be required for the grid you defined.

We could perhaps add a note in the documentation to clarify this.

**Comment by zhangdalang** [comment]
Thanks for the quick response!
My Operating System: Windows 10
Python version: 3.11
QuakeMigrate version: 1.0.3

I'm trying edit iceland_lut.py, node spacing  [1, 1, 0.02]
```
grid_spec.ll_corner = [-19.24363934275664, 64.31947715407385, -1.390]
grid_spec.ur_corner = [-15.204348515198255, 64.3365202025144, 1.390]
grid_spec.node_spacing = [1, 1, 0.02]
```
Increase seismic wave velocity:
```
lut = compute_traveltimes(
    grid_spec,
    stations,
    method="homogeneous",
    phases=["P", "S"],
    vp=5.5,
    vs=3.5,
    log=True,
    save_file=lut_out,
)
```
The detect program is working.
Some result has been generated in outputs\runs\example_run\detect\


But I have a new problem, I want a lookup table that both longitude and latitude are 15 degrees wide.
Unfortunately, I don't understand seismology, I am just a individual developer.
So, within this latitude and longitude range. How many time series data I need? Or what is the calculation formula?
thank you very much.

**Comment by zhangdalang** [comment]
I think I will use parameter:
grid_spec.node_spacing = [1, 1, 0.02] 

vp=5.5,
vs=3.5,

**Comment by hemmelig** [comment]
Hi—could you provide a little more context on what you are hoping to apply QuakeMigrate to? A 15 by 15 degree grid will start to border on the limits of the appropriateness of a Cartesian velocity model. A homogeneous velocity model will also likely be inappropriate.

The window of the time series is given by:

timestep + pre-pad + post-pad

The pre-pad is computed as: long-term window length + 3 * short-term window length
The post-pad is computed as: maximum travel time across the grid + 2 * long-term window length

The maximum travel time is then a function of the size of your grid.

I'm going to close this for now, as the original issue has been resolved.
