### ISSUE TITLE
numpy.product changed to numpy.prod in numpy version2.0 (issue in quakemigrate/signal/trigger.py line 43)

### ISSUE THREAD

**Issue by jamiemccann** [QuakeMigrate/QuakeMigrate#187]
**Describe the bug**
Using latest versions of numpy numpy.product no longer works, and numpy.product is used in line 43 of quakemigrate/signal/trigger.py, changed to numpy.prod in documentation

**To Reproduce**
Create new venv with only dependencies required by quakemigrate as installed with pip install quakemigrate. Run script to create LUT with required input and then run script to trigger

**Expected behavior**
Trigger.py should run smoothly to completion, with final figure summary created if this option is chosen.

**Desktop (please complete the following information):**
 - Operating System: Linux
 - Python version: 3.12.6
 - QuakeMigrate version:1.1.1

**Additional context**

**Comment by TomWinder** [comment]
Hi Jamie, thanks for this. This was fixed here: #179 but hasn't been merged into master or into a release yet. It should be fine to use the "static" trigger, but dynamic won't work before product -->  prod.

@hemmelig perhaps we should just make a separate PR for this individual fix to bundle into 1.1.2?

**Comment by jamiemccann** [comment]
Ah yes understood, thanks very much Tom!

**Comment by hemmelig** [comment]
@TomWinder yes, fixes for things like this should be sent to the latest `patch/vx.x.x` branch and trigger an immediate merge down to master and new release. Feel like their ought to be a way to cherry pick a specific commit from one branch (the fix that's in #179), apply it to a fresh branch from `patch/v1.1.2` and then have git do it's thing later when we merge v.1.2.0 into master. Theoretically..
