### ISSUE TITLE
Re-write NonLinLoc class

### ISSUE THREAD

**Issue by twinder36** [QuakeMigrate/QuakeMigrate#6]
Current workflow to read 3d nlloc lut files:
- read file ==> nlloc_load_file()
- define LUT properties & projection ==> nlloc_regrid() OR nlloc_project_grid()
      ==> some redundancy here and nlloc_project_grid() does not currently work.

Solution:
- make new function to re-map grid parameters from NLLOC .hdr file to LUT class variables etc. (job done at start of nlloc_regrid() ) to be called at end of nlloc_load_file().
- AND/OR re-structure GRID3D / LUT / NonLinLoc classes, so that class inheritance etc. makes more sense.

**Comment by tmgreenfield1101** [comment]
Does it make sense just to save the look-up tables as NonLinLoc files anyway rather than pickled dictionaries. This would then allow the user to provide their own files with no faff converting from one to another.

**Comment by tmgreenfield1101** [comment]
Needs test of lut_io branch

**Comment by twinder36** [comment]
Addressed in re-write of model.py to lut.py.
