### ISSUE TITLE
libgcc-ng

### ISSUE THREAD

**Issue by bvicic** [QuakeMigrate/QuakeMigrate#63]
Hi. I tried installing QuakeMigrate, but fail to do so. I am running latest MacOS.

I removed the libgcc-ng from QuakeMigrate.yml followed by creation of the new env.
When I activate the new env, I tried installing libgcc-ng with the conda command, but I get the 

PackagesNotFoundError: The following packages are not available from current channels:
  - libgcc-ng

error. 

Any idea how to proceed? 

Thanks!

**Comment by hemmelig** [comment]
Hi there

What was the command you used? `conda install libgcc` ? I've passed this on to someone that has installed the package on MacOS.

**Comment by bvicic** [comment]
I used
conda install -c anaconda libgcc-ng

As specified on their website

**Comment by twinder36** [comment]
Hi @bvicic 

Please use: `conda install gcc`

Let me know if this doesn't work.

**Comment by bvicic** [comment]
thanks, it works now!

**Comment by twinder36** [comment]
@bvicic please can you confirm you are now successfully able to install and run QMigrate in this conda environment? Thanks!

**Comment by bvicic** [comment]
Yes, I ran the icequake example without any problems!

Thanks

**Comment by twinder36** [comment]
If you run into further problems that require advice rather than fixes to the code please feel free to email me or Conor on tom.winder@esc.cam.ac.uk or conor.bacon@esc.cam.ac.uk . We can then also add you to the QMigrate slack. Thanks for using the code!
