### ISSUE TITLE
Page QuakeMigrate at ReadtheDocs 

### ISSUE THREAD

**Issue by fontiela** [QuakeMigrate/QuakeMigrate#74]
Just to let you know that the Page QuakeMigrate at ReadtheDocs doesn't exist.

**Comment by twinder36** [comment]
Apologies - there is not currently a ReadtheDocs guide available for the version of the code on 'master'.

Please find the documentation for the development version of the code (to be released very shortly as v1.0.0) here: https://quakemigrate.readthedocs.io/en/readthedocs/index.html . Please contact me (tom.winder@esc.cam.ac.uk) or Conor (conor.bacon@esc.cam.ac.uk) for help using this significantly improved (but currently pre-release) version of the software.

Thanks for your interest in the code!
