### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by paudetseis** [QuakeMigrate/QuakeMigrate#89]
Guys - great looking piece of code! I haven't tried it but will certainly take a look.

Your documentation mentions the lack of support from MacOS or Windows platforms. You should consider using continuous integration tools to automatically test compilation on those systems using virtual machines. There's a certain number of available CI tools (Travis CI is one of the standards) with really good documentation online, but if you need a place to start with Travis you can look here: https://github.com/nfsi-canada/OrientPy/blob/master/.travis.yml.  

Your .travis.yml file will likely be more complicated due to the required installation of NonLinLoc from an external source (i.e., other than through pip or conda - but see `before_install:` in the travis file).

**Comment by hemmelig** [comment]
Hi, and thanks!

We recently finished testing on Windows and macOS and do now support them (see the Installation page). I had meant to update the landing page of the docs! We're waiting until we push the main release (currently on development while we do the last couple of tweaks) before I finish configuring the CI bots, but I'll certainly take a look at how you've configured things. Seeking inspiration from other projects has certainly helped us in the past!

I haven't really decided how to handle the NonLinLoc (optional) backend. It's not strictly necessary to run the code, but it would definitely be useful to make sure everything behaves as expected across different platforms. Thanks for the tip.

**Comment by TomWinder** [comment]
The docs have been updated to reflect the fact that we now support macOS and Windows as well as Linux. Travis CI will hopefully be coming soon..

Thanks for spotting this, @paudetseis !
